---
name: CGI-remote_addr
version: 0.02
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: Enhanced version of CGI.pm's "remote_addr()"
license: perl
resources:
  license: ~
requires:
  CGI: 0
  List::MoreUtils: 0
  Regexp::Common: 0
build_requires:
  Test::More: 0
provides:
  CGI::remote_addr:
    file: lib/CGI/remote_addr.pm
    version: 0.02
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
